matrix:
  include:
    - language: node_js
      node_js:
        - "lts/*"
      before_script:
        - npm install
      script:
        - npm run webpack
    - language: python
      python:
        - 3.9
      install:
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      script:
        - flake8 app
    - language: python
      python:
        - 3.9
      install:
        - pip install -r requirements.txt
        - pip install -r test-requirements.txt
      script:
        - python -m pytest
